if (!window.SITE_CONFIG) document.write('<script src="site-config.js"><\/script>');
const settings = { whatsapp: '9002XXXXX2', phone: '9002XXXXX2', address: 'DHAKURIA', ...(JSON.parse(localStorage.getItem('atelierSettings') || 'null') || {}), ...(window.SITE_CONFIG || {}) };
const defaults = window.SITE_CONFIG?.projects || [];
const projects = JSON.parse(localStorage.getItem('atelierProjects') || 'null') || defaults;
const escapeHtml = value => String(value).replace(/[&<>"']/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[character]));
document.querySelectorAll('body *').forEach(element => { if (element.childElementCount === 0) element.textContent = element.textContent.replace(/CALCUTTA\s*·\s*INDIA/gi, 'KOLKATA').replace(/wherever that is/gi, 'right here in Kolkata'); });
const $ = selector => document.querySelector(selector); $('#year').textContent = new Date().getFullYear(); $('#studio-address').textContent = settings.address; $('#contact-number').textContent = settings.phone; $('#social-whatsapp-link').href = `https://wa.me/${(settings.whatsapp || '').replace(/\D/g,'')}`; $('#project-grid').innerHTML = projects.map(project => `<article class="project-card"><img src="${project.image}" alt="${escapeHtml(project.alt || project.name)}" loading="lazy"><div class="project-card-info"><p>${escapeHtml(project.type)}</p><h3>${escapeHtml(project.name)}</h3></div></article>`).join('');
setupNavigation(); setupBackTop(); setupQueryForm(); setupSocialMedia();
function setupNavigation(){const toggle=$('.menu-toggle');const nav=$('.site-nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});document.querySelectorAll('.nav-dropdown>a').forEach(link=>link.addEventListener('click',event=>{if(window.innerWidth<=760){event.preventDefault();link.parentElement.classList.toggle('submenu-open')}}));nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>nav.classList.remove('open')))}
function setupBackTop(){const button=$('#back-top');window.addEventListener('scroll',()=>button.classList.toggle('visible',scrollY>500));button.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}))}
function setupQueryForm(){const form=$('#query-form');if(!form)return;form.addEventListener('submit',async event=>{event.preventDefault();const status=$('#form-status');const endpoint=window.SITE_CONFIG?.formEndpoint;if(!endpoint){status.textContent='The enquiry form is not connected yet. Please call or WhatsApp us.';return}status.textContent='Sending your enquiry...';try{const response=await fetch(endpoint,{method:'POST',headers:{Accept:'application/json'},body:new FormData(form)});if(!response.ok)throw new Error('Request failed');form.reset();status.textContent='Thank you. Your enquiry is on its way.'}catch{status.textContent='We could not send this yet. Please call or WhatsApp us.'}})}
function setupSocialMedia(){const wrapper=$('.floating-socials');const button=$('.social-toggle');button.addEventListener('click',()=>{const open=wrapper.classList.toggle('open');button.setAttribute('aria-expanded',open);button.setAttribute('aria-label',open?'Close social media links':'Open social media links');$('.social-toggle-mark').textContent=open?'×':'+'})}
